### PR TITLE
Findbugs fixes

### LINKED ISSUE #103: Findbugs issues: NP_NULL_ON_SOME_PATH
Running Findbugs on EWD revealed the following instance of issue NP_NULL_ON_SOME_PATH:

[INFO] Possible null pointer dereference of capabilities in org.finra.jtaf.ewd.impl.DefaultSessionFactory.createCapabilities(Map) [org.finra.jtaf.ewd.impl.DefaultSessionFactory, org.finra.jtaf.ewd.impl.DefaultSessionFactory, org.finra.jtaf.ewd.impl.DefaultSessionFactory] Dereferenced at DefaultSessionFactory.java:[line 226]Null value at DefaultSessionFactory.java:[line 187]Known null at DefaultSessionFactory.java:[line 222] NP_NULL_ON_SOME_PATH

### LINKED ISSUE #104: Findbugs issues: NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
Running Findbugs on EWD revealed the following instance of issue NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE:

[INFO] Possible null pointer dereference in org.finra.jtaf.ewd.impl.DefaultSessionFactory.removeFolders(String, List, int) due to return value of called method [org.finra.jtaf.ewd.impl.DefaultSessionFactory, org.finra.jtaf.ewd.impl.DefaultSessionFactory] Dereferenced at DefaultSessionFactory.java:[line 644]Known null at DefaultSessionFactory.java:[line 644] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE

### LINKED ISSUE #108: Findbugs issues: NP_NULL_PARAM_DEREF
Running Findbugs on EWD revealed the following instance of issue NP_NULL_PARAM_DEREF

[INFO] Null passed for non-null parameter of highlight(Element$HIGHLIGHT_MODES) in org.finra.jtaf.ewd.widget.element.Element.findElement(boolean) [org.finra.jtaf.ewd.widget.element.Element, org.finra.jtaf.ewd.widget.element.Element, org.finra.jtaf.ewd.widget.element.Element] Method invoked at Element.java:[line 694]Null value at Element.java:[line 683]Known null at Element.java:[line 686] NP_NULL_PARAM_DEREF

### PR DESCRIPTION
**Pull request by mikeastarb**
Apologies for the noise in the removal of extra white space.

This PR closes #103, closes #104, and closes #108

I'm open to suggestion on other, perhaps, better ways to do this, so please feel free to make suggestions.

### CODE REVIEW

**Comment by SonOfFlyingPig** [comment]
Are there any more specific exceptions we could throw instead of just Exception? If not, could you create one? We might need to have a conversation about how to handle this since we're going to have to when we do more findbugs/PMD fixes.

**Comment by SonOfFlyingPig** [comment]
We'll handle that generic Exception issue as part of #117

**Comment by mikeastarb** [comment]
Sounds good to me. I'm wasn't too sure what the convention is for our exception handling and digging around for best practices online only gets me as far as opinion wars between what should or shouldn't be checked and if those exceptions should be sub-classes or generics with messages. Do we have a guideline to help make that kind of call?

**Comment by SonOfFlyingPig** [comment]
We do not have an established guideline. Right now EWD has a handful of specialized exceptions. I don't think it would hurt to add a few more, but I wouldn't want that number to explode eventually either. Let's talk about it at the next meeting.

**Pull request merged**
