### PR TITLE
add ability to running on edge

### PR DESCRIPTION
**Pull request by hyaruixi**

### CODE REVIEW

**Comment by SonOfFlyingPig** [comment]
Review comments:

- If we're going to update our selenium dependency, let's move it to the latest (2.53)
- Why did you add the unnecessary import statements (fromthe org.finra.jtaf.ewd.impl package)?
- How about we also allow the user to just specify "edge" as an option (since the other options are all short, lowercase, and one word_)

**Comment by hyaruixi** [comment]
I agree with move selenium dependency to 2.53, and add "edge" as an option for users.
the import thing is my mistake, i didnt notice they are belongs to the same package so I dont need to import.

**Comment by hyaruixi** [comment]
the change for pom file, reason is Starting with version 2.53.0 we need to explicitly include HtmlUnitDriver as a dependency to include it.

**Comment by SonOfFlyingPig** [comment]
Looks good!

**Pull request merged**
